/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.ECarro;
import entidade.ELocatario;
import javax.swing.JOptionPane;
import negocio.NCarro;
import negocio.NLocatario;

/**
 *
 * @author Eduardo
 */
public class CarroCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form CarroCadastro
     */
    public CarroCadastro() {
        initComponents();
        txtCodigo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterarValor.setEnabled(false);
        
        
        
    }
    
    public CarroCadastro(int codigo) {
        this();

        try {
            ECarro carro = new NCarro().consultar(codigo);

            preencherTela(carro);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCarro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPortas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQdePassageiros = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMotor = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterarValor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        txtPlaca = new javax.swing.JTextField();
        txtValorAluguel = new javax.swing.JTextField();
        txtDirecao = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro Carro");

        jPCarro.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Carro"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Modelo do Carro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Placa");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Valor Aluguel");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Direção");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Portas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Quantidade de Passageiros");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Motor");

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/48x48/car add.png"))); // NOI18N
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/48x48/car del.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterarValor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterarValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/48x48/interact.png"))); // NOI18N
        btnAlterarValor.setText("Alterar Valor");
        btnAlterarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarValorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Codigo");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/48x48/car pesq.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCarroLayout = new javax.swing.GroupLayout(jPCarro);
        jPCarro.setLayout(jPCarroLayout);
        jPCarroLayout.setHorizontalGroup(
            jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCarroLayout.createSequentialGroup()
                        .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCarroLayout.createSequentialGroup()
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCarroLayout.createSequentialGroup()
                                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(txtQdePassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7)
                                        .addGroup(jPCarroLayout.createSequentialGroup()
                                            .addComponent(txtDirecao)
                                            .addGap(57, 57, 57)
                                            .addComponent(txtPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPCarroLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(99, 99, 99)
                                            .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel5)
                                                .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                                    .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 71, Short.MAX_VALUE)
                        .addComponent(btnAlterarValor))
                    .addGroup(jPCarroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92)
                        .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCarroLayout.setVerticalGroup(
            jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQdePassageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            validartela();
            ECarro carro = new ECarro();

            if (!txtCodigo.getText().isEmpty()) {
                carro.setCodigo(Integer.parseInt(txtCodigo.getText()));
            }

            //String pessoaf = btnGTipo_pessoa.getSelection().getActionCommand();
            carro.setDirecao(txtDirecao.getText());
            carro.setNome_modelo(txtModelo.getText());
            carro.setMotor(txtMotor.getText());
            carro.setPlaca(txtPlaca.getText());
            carro.setPortas(txtPortas.getText());
            carro.setPassageiros(txtQdePassageiros.getText());
            carro.setValoraluguel(Double.parseDouble(txtValorAluguel.getText()));

            NCarro negocio = new NCarro();
            negocio.salvar(carro);

            JOptionPane.showMessageDialog(null, "Carro cadastrado com sucesso");
            limpartela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            int resposta = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do Carro?", "ADS Locadora Veículos", JOptionPane.YES_NO_OPTION);

            if (resposta == JOptionPane.YES_NO_OPTION) {
                int codigo = Integer.parseInt(txtCodigo.getText());
                new NLocatario().excluir(codigo);
                JOptionPane.showMessageDialog(null, "Carro excluido com sucesso");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarValorActionPerformed
        // TODO add your handling code here:
        try {
            ECarro carro = new ECarro();
            
            carro.setValoraluguel(Double.parseDouble(txtValorAluguel.getText()));
            
            NCarro negocio = new NCarro();
            negocio.alterar(Double.parseDouble(txtValorAluguel.getText()) , Integer.parseInt(txtCodigo.getText()));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAlterarValorActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        try {
            String codigo = JOptionPane.showInputDialog("" + "Digite o código do carro para consulta");

            if (codigo == null || codigo.equals("")) {
                throw new Exception("Digite o código para consulta");
            }

            int intCodigo = Integer.parseInt(codigo);
            
            ECarro carro = new NCarro().consultar(intCodigo);
            
            if (carro.getCodigo() != 0) {
                preencherTela(carro);
            }else{
                JOptionPane.showMessageDialog(null, "Carro inexistente");
            }
            
            btnAlterarValor.setEnabled(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "É necessário informar um código válido!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarValor;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPCarro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDirecao;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPortas;
    private javax.swing.JTextField txtQdePassageiros;
    private javax.swing.JTextField txtValorAluguel;
    // End of variables declaration//GEN-END:variables

    private void validartela() throws Exception {
        if (txtModelo.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo modelo do carro!");
        }
        if (txtPlaca.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo placa!");
        }
        if (txtValorAluguel.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo valor do aluguel!");
        }
        if (txtDirecao.getText().isEmpty()) {

            throw new Exception("É necessário preencher o campo direção!");

        }
        if (txtPortas.getText().isEmpty()) {

            throw new Exception("É necessário preencher o campo portas!");

        }
        if (txtQdePassageiros.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo passageiros!");
        }
        if (txtMotor.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo motor!");
        }
    }

    private void limpartela() {
        txtCodigo.setText("");
        txtDirecao.setText("");
        txtModelo.setText("");
        txtMotor.setText("");
        txtPlaca.setText("");
        txtPortas.setText("");
        txtQdePassageiros.setText("");
        txtValorAluguel.setText("");
    }

    private void preencherTela(ECarro carro) {
        txtCodigo.setText(carro.getCodigo() + "");
        txtDirecao.setText(carro.getDirecao());
        txtModelo.setText(carro.getNome_modelo());
        txtMotor.setText(carro.getMotor());
        txtPlaca.setText(carro.getPlaca());
        txtPortas.setText(carro.getPortas());
        txtQdePassageiros.setText(carro.getPassageiros());
        txtValorAluguel.setText(carro.getValoraluguel() + "");
        btnExcluir.setEnabled(true);
        btnAlterarValor.setEnabled(true);
    }
    
}
