/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import classededados.Data;
import entidade.ECarro;
import entidade.ELocacao;
import entidade.ELocatario;
import java.sql.SQLException;
import java.util.Vector;
import javafx.scene.chart.PieChart;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NCarro;
import negocio.NLocacao;
import negocio.NLocatario;

/**
 *
 * @author Eduardo
 */
public class Locacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Movimentacao
     */
    public Locacao() throws SQLException {
        initComponents();
        try {
            carregarTabelaLocatario(new ELocatario());
            carregarTabelaCarro(new ECarro());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocatario = new javax.swing.JTable();
        btnLocar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarro = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDataRetirada = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataDevolucao = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLocalRetirada = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Locação");

        tblLocatario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblLocatario);

        btnLocar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/48x48/Car loc.png"))); // NOI18N
        btnLocar.setText("Locar Carro");
        btnLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocarActionPerformed(evt);
            }
        });

        tblCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblCarro);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data de Retirada");

        try {
            txtDataRetirada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Data de Devolução");

        try {
            txtDataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Local de Retirada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtLocalRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(282, 282, 282))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocalRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(btnLocar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocarActionPerformed
        // TODO add your handling code here:
        try {
            validartela();
            ELocacao locacao = new ELocacao();
            //ECarro carro = new ECarro();
            String datar = txtDataRetirada.getText();
            String datad = txtDataDevolucao.getText();

            Data dr = new Data(datar, Data.BarraSemHora);
            txtDataRetirada.setText(dr.getDataString());
            
            Data dd = new Data(datad, Data.BarraSemHora);
            txtDataDevolucao.setText(dd.getDataString());

            Data Hoje = new Data();

            if (Hoje.getTimestamp().getTime() > dr.getTimestamp().getTime()) {
                JOptionPane.showMessageDialog(rootPane, "Data informada já passou!");
            } 

            //String pessoaf = btnGTipo_pessoa.getSelection().getActionCommand();
            locacao.setDatadedevolucao(datar);
            locacao.setDataretirada(datad);
            locacao.setLocalderetirada(txtLocalRetirada.getText());
            int indicelinhac = tblCarro.getSelectedRow();
            //locacao.setCodigocarro((ECartblCarro.getValueAt(indicelinhac, 0));
            int indicelinhal = tblLocatario.getSelectedRow();
            //locacao.setCodigolocador((ELocatario) tblLocatario.getValueAt(indicelinhal, 0));
            
            

            NLocacao negocio = new NLocacao();
            negocio.locar(locacao);

            JOptionPane.showMessageDialog(null, "Carro Alugado");
            limpartela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnLocarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCarro;
    private javax.swing.JTable tblLocatario;
    private javax.swing.JFormattedTextField txtDataDevolucao;
    private javax.swing.JFormattedTextField txtDataRetirada;
    private javax.swing.JTextField txtLocalRetirada;
    // End of variables declaration//GEN-END:variables

    private void carregarTabelaLocatario(ELocatario eLocatario) throws SQLException {
        Vector<String> cabecalho = new Vector<String>();
        cabecalho.add("Codígo");
        cabecalho.add("Nome");
        cabecalho.add("Endereço");
        cabecalho.add("Telefone");
        cabecalho.add("Tipo Pessoa");
        cabecalho.add("Email");
        cabecalho.add("Tipo CNH");

        Vector detalhe = new Vector();

        for (ELocatario item : new NLocatario().listar(eLocatario.getNome())) {
            Vector<String> linha = new Vector<String>();
            linha.add(item.getCodigo() + "");
            linha.add(item.getNome());
            linha.add(item.getEndereco());
            linha.add(item.getTelefone());
            linha.add(item.getTipo_pessoa());
            linha.add(item.getEmail());
            linha.add(item.getTipoCNH());
            detalhe.add(linha);
        }

        tblLocatario.setModel(new DefaultTableModel(detalhe, cabecalho));
    }

    private void validartela() throws Exception {

        if (txtDataDevolucao.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo data de devolução!");
        }
        if (txtDataRetirada.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo data de retirada!");
        }
        if (txtLocalRetirada.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo local de retirada!");
        }

    }

    private void limpartela() {

        txtDataDevolucao.setText("");
        txtDataRetirada.setText("");
        txtLocalRetirada.setText("");
    }

    private void carregarTabelaCarro(ECarro parametro) throws SQLException {
        Vector<String> cabecalho = new Vector<String>();
        cabecalho.add("Codígo");
        cabecalho.add("Nome do Carro");
        cabecalho.add("Placa");
        cabecalho.add("Valor do Aluguel");
        cabecalho.add("Direção");
        //cabecalho.add("Portas");
        cabecalho.add("Passageiros");
        cabecalho.add("Motor");

        Vector detalhe = new Vector();

        for (ECarro item : new NCarro().listar(parametro.getNome_modelo())) {
            Vector<String> linha = new Vector<String>();
            linha.add(item.getCodigo() + "");
            linha.add(item.getNome_modelo());
            linha.add(item.getPlaca());
            linha.add(item.getValoraluguel() + "");
            linha.add(item.getDirecao());
            //linha.add(item.getPortas());
            linha.add(item.getPassageiros());
            linha.add(item.getMotor());
            detalhe.add(linha);
        }

        tblCarro.setModel(new DefaultTableModel(detalhe, cabecalho));
    }

}
