/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import classededados.Data;
import entidade.ECarro;
import entidade.ELocacao;
import entidade.ELocatario;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NCarro;
import negocio.NLocacao;
import negocio.NLocatario;

/**
 *
 * @author Eduardo
 */
public class Locacao2 extends javax.swing.JInternalFrame {
    private Object parametro;
    public String SeleLocat;
    public String SeleCarro;

    /**
     * Creates new form Locacao2
     */
    public Locacao2() {
        initComponents();
        try {
            carregarTabelaLocatario(new ELocatario());
            carregarTabelaCarro(new ECarro());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        this.cmbLocalRetirada.removeAllItems();
        this.cmbLocalRetirada.addItem("Selecione");
        this.cmbLocalRetirada.addItem("Loja");
        this.cmbLocalRetirada.addItem("Aeroporto");
        this.cmbLocalRetirada.addItem("Rodoviária");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocatario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDataRetirada = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataDevolucao = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLocar = new javax.swing.JButton();
        cmbLocalRetirada = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Locação do Carro");

        tblLocatario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblLocatario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Selecionar Locatário", jPanel1);

        tblCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblCarro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Selecionar Carro", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Data de Retirada");

        try {
            txtDataRetirada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data de Devolução");

        try {
            txtDataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Local de Retirada");

        btnLocar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/48x48/Car loc.png"))); // NOI18N
        btnLocar.setText("Locar Carro");
        btnLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDataRetirada))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDataDevolucao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbLocalRetirada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbLocalRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocarActionPerformed
        // TODO add your handling code here:
        try {
            validartela();
            ELocacao locacao = new ELocacao();
            //ECarro carro = new ECarro();
            String datar = txtDataRetirada.getText();
            String datad = txtDataDevolucao.getText();

            Data dr = new Data(datar, Data.BarraSemHora);
            txtDataRetirada.setText(dr.getDataString());
            
            Data dd = new Data(datad, Data.BarraSemHora);
            txtDataDevolucao.setText(dd.getDataString());

            Data Hoje = new Data();

            if (Hoje.getTimestamp().getTime() > dr.getTimestamp().getTime()) {
                JOptionPane.showMessageDialog(rootPane, "Data informada já passou!");
            } 

            //String pessoaf = btnGTipo_pessoa.getSelection().getActionCommand();
            locacao.setDatadedevolucao(datar);
            locacao.setDataretirada(datad);
            locacao.setLocalderetirada((String) cmbLocalRetirada.getSelectedItem());
            
            int indicelinhal = tblLocatario.getSelectedRow();
            int codigoLocatario = (int)tblLocatario.getValueAt(indicelinhal, 0);
            
            
            ELocatario eLocatario = new ELocatario();
            NLocatario nLocatario = new NLocatario();
            
            eLocatario = nLocatario.consultar(codigoLocatario);
            
            locacao.setLocatario(eLocatario);

            
            
            int indicelinhac = tblCarro.getSelectedRow();
            int codigocarro = (int)tblCarro.getValueAt(indicelinhac, 0);   
                
            ECarro eCarro = new ECarro();
            NCarro nCarro = new NCarro();
            
            eCarro =  nCarro.consultar(codigocarro);
            
            locacao.setCarro(eCarro);

            NLocacao negocio = new NLocacao();
            negocio.locar(locacao);

            JOptionPane.showMessageDialog(null, "Carro Alugado");
            limpartela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnLocarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocar;
    private javax.swing.JComboBox cmbLocalRetirada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCarro;
    private javax.swing.JTable tblLocatario;
    private javax.swing.JFormattedTextField txtDataDevolucao;
    private javax.swing.JFormattedTextField txtDataRetirada;
    // End of variables declaration//GEN-END:variables

    private void carregarTabelaLocatario(ELocatario eLocatario) throws SQLException {
        Vector<Object> cabecalho = new Vector<Object>();
        cabecalho.add("Codígo");
        cabecalho.add("Nome");
        cabecalho.add("Endereço");
        cabecalho.add("Telefone");
        cabecalho.add("Tipo Pessoa");
        cabecalho.add("Email");
        cabecalho.add("Tipo CNH");

        Vector detalhe = new Vector();

        for (ELocatario item : new NLocatario().listar(eLocatario.getNome())) {
            Vector<Object> linha = new Vector<Object>();
            linha.add(item.getCodigo());
            linha.add(item.getNome());
            linha.add(item.getEndereco());
            linha.add(item.getTelefone());
            linha.add(item.getTipo_pessoa());
            linha.add(item.getEmail());
            linha.add(item.getTipoCNH());
            detalhe.add(linha);
        }

        tblLocatario.setModel(new DefaultTableModel(detalhe, cabecalho));
    }

    private void carregarTabelaCarro(ECarro parametro) throws SQLException {
         Vector<Object> cabecalho = new Vector<Object>();
        cabecalho.add("Codígo");
        cabecalho.add("Nome do Carro");
        cabecalho.add("Placa");
        cabecalho.add("Valor do Aluguel");
        cabecalho.add("Direção");
        //cabecalho.add("Portas");
        cabecalho.add("Passageiros");
        cabecalho.add("Motor");

        Vector detalhe = new Vector();

        for (ECarro item : new NCarro().listar(parametro.getNome_modelo())) {
            Vector<Object> linha = new Vector<Object>();
            linha.add(item.getCodigo());
            linha.add(item.getNome_modelo());
            linha.add(item.getPlaca());
            linha.add(item.getValoraluguel() + "");
            linha.add(item.getDirecao());
            //linha.add(item.getPortas());
            linha.add(item.getPassageiros());
            linha.add(item.getMotor());
            detalhe.add(linha);
        }

        tblCarro.setModel(new DefaultTableModel(detalhe, cabecalho));
    }
    
    private void validartela() throws Exception {

        if (txtDataDevolucao.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo data de devolução!");
        }
        if (txtDataRetirada.getText().isEmpty()) {
            throw new Exception("É necessário preencher o campo data de retirada!");
        }
        if (cmbLocalRetirada.getSelectedIndex() == 0) {
            throw new Exception("É necessário preencher o campo Local de Retirada!");
        }

    }

    private void limpartela() {

        txtDataDevolucao.setText("");
        txtDataRetirada.setText("");
        cmbLocalRetirada.setSelectedIndex(0);
    }
}
