/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.TexturePaint;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eduardo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        PnlImagem imagem = new PnlImagem();

        this.pnlPrincipal.add(imagem);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        pnlPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadastroCliente = new javax.swing.JMenuItem();
        mnuCadastrarCarro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuPesquisaLocatario = new javax.swing.JMenuItem();
        mnuPesquisaCarro = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuLocarCarro = new javax.swing.JMenuItem();
        mnuPagamento = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADS LOCADORA");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        mnuCadastro.setText("Novo");

        mnuCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuCadastroCliente.setText("Cadastrar Locatário");
        mnuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroCliente);

        mnuCadastrarCarro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuCadastrarCarro.setText("Cadastar Carro");
        mnuCadastrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarCarroActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastrarCarro);

        jMenuBar1.add(mnuCadastro);

        jMenu2.setText("Pesquisa");

        mnuPesquisaLocatario.setText("Pesquisar Locatário");
        mnuPesquisaLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesquisaLocatarioActionPerformed(evt);
            }
        });
        jMenu2.add(mnuPesquisaLocatario);

        mnuPesquisaCarro.setText("Pesquisar Carro");
        mnuPesquisaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesquisaCarroActionPerformed(evt);
            }
        });
        jMenu2.add(mnuPesquisaCarro);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Movimentação");

        mnuLocarCarro.setText("Locar Carro");
        mnuLocarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLocarCarroActionPerformed(evt);
            }
        });
        jMenu3.add(mnuLocarCarro);

        mnuPagamento.setText("Pagamento");
        mnuPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPagamentoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuPagamento);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastrarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarCarroActionPerformed
        // TODO add your handling code here:
        try {

            CarroCadastro janela = new CarroCadastro();
            this.pnlPrincipal.add(janela);
            janela.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_mnuCadastrarCarroActionPerformed

    private void mnuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroClienteActionPerformed
        // TODO add your handling code here:
        try {

            LocatarioCadastro janela = new LocatarioCadastro();
            this.pnlPrincipal.add(janela);
            janela.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_mnuCadastroClienteActionPerformed

    private void mnuPesquisaLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesquisaLocatarioActionPerformed
        // TODO add your handling code here:
        try {

            LocatarioPesquisa janela = new LocatarioPesquisa(pnlPrincipal);
            this.pnlPrincipal.add(janela);
            janela.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_mnuPesquisaLocatarioActionPerformed

    private void mnuPesquisaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesquisaCarroActionPerformed
        // TODO add your handling code here:
        try {

            CarroPesquisa janela = new CarroPesquisa(pnlPrincipal);
            this.pnlPrincipal.add(janela);
            janela.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_mnuPesquisaCarroActionPerformed

    private void mnuLocarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLocarCarroActionPerformed
        // TODO add your handling code here:
        try {

            Locacao2 janela = new Locacao2();
            this.pnlPrincipal.add(janela);
            janela.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage ());
        }
    }//GEN-LAST:event_mnuLocarCarroActionPerformed

    private void mnuPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPagamentoActionPerformed
        // TODO add your handling code here:
         try {
            Pagamento janela = new Pagamento();
            this.pnlPrincipal.add(janela);
            janela.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_mnuPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCadastrarCarro;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCadastroCliente;
    private javax.swing.JMenuItem mnuLocarCarro;
    private javax.swing.JMenuItem mnuPagamento;
    private javax.swing.JMenuItem mnuPesquisaCarro;
    private javax.swing.JMenuItem mnuPesquisaLocatario;
    private javax.swing.JDesktopPane pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
